### PR TITLE
ovm client should supports recursive challenge table

### PR DESCRIPTION
**Pull request by syuhei176**
### Why

To get correct "challenge" and "challengeInputs" data for requesting challenge to contract.

### Tasks

* update decision data structure. change challenges array to one challenge.
* update challenge data structure. change one challengeInput to challegeInputs array.
* update challenge of ForAllSuchThatDecider.ts
* update challenge of AndDecider.ts

### CODE REVIEW

**Comment by tkmct** [comment]
why should we have `challengeInput: [null]`?

**Comment by syuhei176** [comment]
> why should we have `challengeInput: [null]`?

This is "∅":empty input in this table.
https://github.com/cryptoeconomicslab/gazelle-website/blob/master/pages/docs/core-spec/README.md#valid-challenge

the test case using empty input in contract is here.
https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/ovm-ethereum-generator/test/ForTestPredicateTestCase.ts#L29

**Comment by syuhei176** [comment]
I'll add comment later

**Comment by syuhei176** [comment]
I think we can remove `null` by modifying generator. let's talk about it.

**Comment by syuhei176** [comment]
ah, wait. we don't need `null` for Not, Or and There exists.

**Comment by syuhei176** [comment]
updated

**Comment by syuhei176** [comment]
changed challengeInputs type to `Bytes[]` from `(Bytes | null)[]`.

**Comment by tkmct** [comment]
Thank you!
I think the most inner challenge should be returned as challengeProperty. Is this understanding correct?

Test of later merged PR looks failing

**Comment by syuhei176** [comment]
> Thank you!
> I think the most inner challenge should be returned as challengeProperty. Is this understanding correct?
> 
> Test of later merged PR looks failing

What challengeProperty is in this context??

**Comment by syuhei176** [comment]
test fixed!

I'm afraid of failing [this test](https://github.com/cryptoeconomicslab/wakkanay/pull/284)

**Comment by tkmct** [comment]
> @tkmct What is challengeProperty in this context??
`challenge.property` which was `challenges[i].property` before

**Comment by syuhei176** [comment]
@tkmct ok, I think the challenge of the most outer(shallow) property should be return.

**Comment by tkmct** [comment]
okay, thanks

**Pull request merged**
