### PR TITLE
Clean verifier test code

### PR DESCRIPTION
**Pull request by syuhei176**

### CODE REVIEW

**Comment by tkmct** [comment]
can you just use this line and remove conseiljs from dependency?
https://github.com/cryptoeconomicslab/wakkanay/pull/84/files#diff-65f2a818b87ed8ef1dc6b988ec2aae68R10

**Comment by syuhei176** [comment]
> LGTM.
> heavily duplicated #84

oopss

**Comment by tkmct** [comment]
Then basically everything should be fine.

**Comment by syuhei176** [comment]
@tkmct rebased this PR on #84. Is it OK?

**Comment by tkmct** [comment]
oops, I think this is cleaner. I put redundant stuff.
I think you can just put one line of code and remove conseiljs from dependencies.
That's simple and good in my opinion!!

**Comment by tkmct** [comment]
Thank you!!

**Comment by syuhei176** [comment]
ok, so I'll merge.

**Pull request merged**
