### PR TITLE
add TokenManager to handle decimal

### PR DESCRIPTION
**Pull request by syuhei176**

### CODE REVIEW

**Comment by tkmct** [comment]
Do we need both `private tokenContracts: Map<string, IERC20Contract> = new Map()` and `TokenContractManager`?

**Comment by syuhei176** [comment]
@tkmct the key of tokenContracts is DepositContractAddress. I thought TokenManager should not have responsibility to manage DepositContract at first. But If we want to manage both DepositContract and TokenContract in TokenManager. We can combine them.

**Comment by tkmct** [comment]
ah okay, I got it. it's better to manage them in one place in my opinion. what do you think?

**Comment by syuhei176** [comment]
agree, but I'm not sure now. I just try.

**Comment by syuhei176** [comment]
removed tokenContracts Map for LightClient.

**Pull request merged**
